title: Pythonによる気象データサイエンス
author: 榎本剛

execute:
  execute_notebooks: "off"

parse:
  myst_enable_extensions:
    - colon_fence
    - amsmath
    - dollarmath

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_default_style: unsrt
    bibtex_reference_style: label

#latex:
#  latex_engine: uplatex
#  use_jupyterbook_latex : true
